{{- if and .Values.prometheus.enabled .Values.prometheus.ingressinternal.enabled -}}
  {{- $pathType := .Values.prometheus.ingressinternal.pathType | default "ImplementationSpecific" -}}
  {{- $serviceName := printf "%s-%s" (include "kube-prometheus-stack.fullname" .) "prometheus" -}}
  {{- $servicePort := .Values.prometheus.ingressinternal.servicePort | default .Values.prometheus.service.port -}}
  {{- $routePrefix := list .Values.prometheus.prometheusSpec.routePrefix -}}
  {{- $paths := .Values.prometheus.ingressinternal.paths | default $routePrefix -}}
  {{- $apiIsStable := eq (include "kube-prometheus-stack.ingress.isStable" .) "true" -}}
  {{- $ingressSupportsPathType := eq (include "kube-prometheus-stack.ingress.supportsPathType" .) "true" -}}
apiVersion: {{ include "kube-prometheus-stack.ingress.apiVersion" . }}
kind: Ingress
metadata:
{{- if .Values.prometheus.ingressinternal.annotations }}
  annotations:
{{ toYaml .Values.prometheus.ingressinternal.annotations | indent 4 }}
{{- end }}
  name: {{ $serviceName }}-internal
  namespace: {{ template "kube-prometheus-stack.namespace" . }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
{{- if .Values.prometheus.ingress.labels }}
{{ toYaml .Values.prometheus.ingress.labels | indent 4 }}
{{- end }}
spec:
  {{- if $apiIsStable }}
  {{- if .Values.prometheus.ingressinternal.ingressClassName }}
  ingressClassName: {{ .Values.prometheus.ingressinternal.ingressClassName }}
  {{- end }}
  {{- end }}
  rules:
  {{- if .Values.prometheus.ingressinternal.hosts }}
  {{- range $host := .Values.prometheus.ingressinternal.hosts }}
    - host: {{ tpl $host $ }}
      http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            {{- if and $pathType $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
    {{- end }}
    {{- end -}}
  {{- end -}}
  {{- else }}
    - http:
        paths:
  {{- range $p := $paths }}
          - path: {{ tpl $p $ }}
            {{- if and $pathType $ingressSupportsPathType }}
            pathType: {{ $pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ $serviceName }}
                port:
                  number: {{ $servicePort }}
              {{- else }}
              serviceName: {{ $serviceName }}
              servicePort: {{ $servicePort }}
  {{- end }}
  {{- end -}}
  {{- end -}}
  {{- if .Values.prometheus.ingressinternal.tls }}
  tls:
{{ tpl (toYaml .Values.prometheus.ingressinternal.tls | indent 4) . }}
  {{- end -}}
{{- end -}}